# Example user configuration file
# Copy this to ~/.cc-filter/config.yaml to customize rules

patterns:
  # Add custom patterns here
  - name: "custom_api_key"
    regex: 'CUSTOM_API_KEY=([a-zA-Z0-9]{32})'
    replacement: "***FILTERED***"
    
  # Override default patterns by using same name
  - name: "openai_keys"
    regex: 'sk-[a-zA-Z0-9]{48}'
    replacement: "***CUSTOM_FILTERED***"

# Add additional file patterns to block
file_blocks:
  - "*.secret"
  - "private-config.json"

# Add additional search terms to block  
search_blocks:
  - "mycompany_token"
  - "internal_key"

# Add additional command patterns to block
command_blocks:
  - "cat.*private"
  - "grep.*internal"