name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          LDFLAGS="-X main.version=$VERSION"
          if [ "$GOOS" = "windows" ]; then
            go build -ldflags "$LDFLAGS" -o cc-filter-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          else
            go build -ldflags "$LDFLAGS" -o cc-filter-${{ matrix.goos }}-${{ matrix.goarch }}
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: cc-filter-*